"""
main.py
-------
Audit Evidence Analyser API

Endpoints
---------
GET  /          → health check
POST /analyse   → upload a CSV, get back risk-flagged rows as JSON
GET  /docs      → Swagger UI (auto-generated by FastAPI)

Run locally:
    uvicorn main:app --reload

Deploy to Render:
    Start command: uvicorn main:app --host 0.0.0.0 --port $PORT
"""

import io
import pandas as pd

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import Any

from analyser import analyse


# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Audit Evidence Analyser API",
    description=(
        "Upload a CSV of audit evidence. "
        "The API runs statistical exception analysis (null checks, z-score, IQR) "
        "and returns risk-flagged rows with a risk score and plain-English reason. "
        "\n\n"
        "Built by Om Dhede — KPMG IT Audit Analyst × AI & Data Science engineer."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten this in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Frontend — serve index.html at /ui
# ---------------------------------------------------------------------------

@app.get("/ui", include_in_schema=False)
def serve_ui():
    """Serve the React-less SPA frontend."""
    return FileResponse("frontend/index.html")


# ---------------------------------------------------------------------------
# Response models  (Pydantic → Swagger docs auto-generated)
# ---------------------------------------------------------------------------

class FlaggedRow(BaseModel):
    row_index:  int
    risk_score: int
    flags:      list[str]
    row_data:   dict[str, Any]

class AnalysisResponse(BaseModel):
    filename:        str
    total_rows:      int
    flagged_rows:    int
    high_risk_rows:  int          # risk_score >= 70
    results:         list[FlaggedRow]

class HealthResponse(BaseModel):
    status:  str
    message: str


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/", response_model=HealthResponse, tags=["Health"])
def health_check():
    """Simple health check — confirms the API is running."""
    return {
        "status":  "ok",
        "message": "Audit Evidence Analyser API is running. POST a CSV to /analyse.",
    }


@app.post("/analyse", response_model=AnalysisResponse, tags=["Analysis"])
async def analyse_csv(file: UploadFile = File(..., description="CSV file of audit evidence")):
    """
    Upload a CSV file and receive a list of exception-flagged rows.

    **What the engine checks:**
    - **Missing values** — any cell that is null / blank (+20 pts per field)
    - **Z-score outliers** — values more than 3 standard deviations from the column mean (+up to 30 pts)
    - **IQR range violations** — values outside Q1−1.5×IQR … Q3+1.5×IQR (+15 pts)

    **Risk score bands:**
    - 70–100 → High risk (likely exception)
    - 40–69  → Medium risk (review recommended)
    - 1–39   → Low risk (minor anomaly)

    **Example use case:** Upload a journal entry population CSV.
    The API flags entries with unusually large amounts, missing approver names, or
    blank GL codes — exactly the exception-identification work done in SOX ITGC testing.
    """

    # --- Validate file type ---
    if not file.filename.endswith(".csv"):
        raise HTTPException(
            status_code=400,
            detail="Only CSV files are supported. Please upload a .csv file.",
        )

    # --- Read CSV ---
    try:
        contents = await file.read()
        df = pd.read_csv(io.StringIO(contents.decode("utf-8")))
    except Exception as e:
        raise HTTPException(
            status_code=422,
            detail=f"Could not parse CSV: {str(e)}",
        )

    if df.empty:
        raise HTTPException(status_code=422, detail="The uploaded CSV is empty.")

    if len(df.columns) < 1:
        raise HTTPException(status_code=422, detail="CSV must have at least one column.")

    # --- Run analysis ---
    flagged = analyse(df)

    high_risk = [r for r in flagged if r["risk_score"] >= 70]

    return AnalysisResponse(
        filename       = file.filename,
        total_rows     = len(df),
        flagged_rows   = len(flagged),
        high_risk_rows = len(high_risk),
        results        = flagged,
    )
